config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users

  root to: "posts#index"

  resources :posts, only: :index do
    resources :comments, except: [:show, :destroy, :edit, :update], shallow: true
  end

  namespace :blog_author do
    resources :posts, except: [:show, :update, :edit] do
      resources :comments, except: [:show, :update, :edit], shallow: true
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_author.rb
class BlogAuthor < User
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, foreign_key: "author_id", class_name: "User"
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, foreign_key: "author_id", class_name: "User"

  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, foreign_key: "author_id", class_name: "Post", dependent: :destroy
  has_many :comments, foreign_key: "author_id", class_name: "Comment", dependent: :destroy

  validates :login, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource)
    current_user.is_author ? blog_author_posts_path : (stored_location_for(resource) || root_path)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:is_author, :login])
  end
end

app/controllers/blog_author/base_controller.rb
class BlogAuthor::BaseController < ApplicationController
  layout 'blog_author'

  before_action :authenticate_user!
  before_action :blog_author_required!

  private

  def blog_author_required!
    redirect_to root_path, alert: 'You are not authorised to view this page,' unless current_user.is_a?(BlogAuthor)
  end
end

app/controllers/blog_author/comments_controller.rb
class BlogAuthor::CommentsController < ApplicationController
  def index
    @post = Post.find(params[:post_id])
    @comments = Comment.all
  end

  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
  end

  def create
    @comment = current_user.comments.build(comment_params)
    @comment.post = Post.find(params[:post_id])
    if @comment.save
      redirect_to blog_author_post_comments_path(@comment.post)
    else
      render :new
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to blog_author_post_comments_path(@comment.post)
  end

  private

  def comment_params
    params.require(:comment).permit( :body)
  end
end

app/controllers/blog_author/posts_controller.rb
class BlogAuthor::PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(posts_params)
    if @post.save
      redirect_to blog_author_posts_path
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to blog_author_posts_path
  end

  private

  def posts_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @post = Post.find(params[:post_id])
    @comments = Comment.all
  end

  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
  end

  def create
    @comment = current_user.comments.build(comment_params)
    @comment.post = Post.find(params[:post_id])
    if @comment.save
      redirect_to post_comments_path(@comment.post)
    else
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit( :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(posts_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def posts_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_messages
    flash.map { |key, msg| (content_tag :p, sanitize(msg, { attributes: %w(target href) }),
                                        :id => key, :class => 'flash ' + key) }.join.html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/blog_author/comments/_comment.html.erb
<tr>
  <td><%= comment.author.login %></td>
  <td><%= comment.body %></td>
  <td><%= comment.created_at %></td>
  <% if comment.author == current_user %>
    <td><%= link_to 'Delete',
                    blog_author_comment_path(comment),
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</tr>

app/views/blog_author/comments/index.html.erb
<h1> <%= @post.title %></h1>
<p><%= @post.body %></p>

<%= link_to 'Leave comment', new_blog_author_post_comment_path(@post) %>

<table class="table">
  <%= render @comments %>
</table>

<%= link_to 'Back', blog_author_posts_path %>

app/views/blog_author/comments/new.html.erb
<%= form_with model: [:blog_author, @post, @comment], local: true do |form| %>
  <%= render 'shared/errors', resource: @comment %>

  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body, id: :comment_body %><br>
  </p>

  <p><%= form.submit %></p>
<% end %>

<%= link_to 'Back', blog_author_post_comments_path(@post) %>

app/views/blog_author/posts/_post.html.erb
<tr>
  <td><%= post.author.login %></td>
  <td><%= post.title %></td>
  <td><%= post.body %></td>
  <td><%= post.created_at %></td>
  <td><%= link_to 'Show', blog_author_post_comments_path(post) %></td>
  <% if post.author == current_user %>
    <td><%= link_to 'Delete',
                    blog_author_post_path(post),
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</tr>

app/views/blog_author/posts/index.html.erb
<h1> All posts </h1>

<%= link_to 'Create new post', new_blog_author_post_path %>

<table class="table">
  <tr>
    <th>Author</th>
    <th>Title</th>
    <th>Content</th>
    <th>Time</th>
    <th colspan="1">Watch comments</th>
  </tr>
  <%= render @posts %>
</table>

app/views/blog_author/posts/new.html.erb
<%= form_with model: [:blog_author, @post], local: true do |form| %>
  <%= render 'shared/errors', resource: @post %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title, id: :post_title%><br>
  </p>

  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body, id: :post_body%><br>
  </p>

  <p><%= form.submit %></p>
<% end %>

<%= link_to 'Back', blog_author_posts_path %>

app/views/comments/_comment.html.erb
<tr>
  <td><%= comment.author.login %></td>
  <td><%= comment.body %></td>
  <td><%= comment.created_at %></td>
</tr>

app/views/comments/index.html.erb
<h1> <%= @post.title %></h1>
<p><%= @post.body %></p>

<%= link_to 'Leave comment', new_post_comment_path(@post) %>

<table class="table">
  <%= render @comments %>
</table>

<%= link_to 'Back', posts_path %>

app/views/comments/new.html.erb
<%= form_with model: [@post, @comment], local: true do |form| %>
  <%= render 'shared/errors', resource: @comment %>

  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body, id: :comment_body %><br>
  </p>

  <p><%= form.submit %></p>
<% end %>

<%= link_to 'Back', post_comments_path(@post) %>

app/views/layouts/_navbar_for_logged_in.html.erb
<p>Welcome, <b><%= current_user.email %></b></p>
<p><%= link_to "Exit", destroy_user_session_path, method: :delete %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestTask7</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </head>

  <body>
  <% if user_signed_in? %>
    <%= render "layouts/navbar_for_logged_in" %>
  <% end %>
  <%= flash_messages %>
  <%= yield %>
  </body>
</html>

app/views/layouts/blog_author.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestTask7</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<% if user_signed_in? %>
  <%= render "layouts/navbar_for_logged_in" %>
<% end %>
<%= flash_messages %>
<%= yield %>
</body>
</html>

app/views/posts/_post.html.erb
<tr>
  <td><%= post.author.login %></td>
  <td><%= post.title %></td>
  <td><%= post.body %></td>
  <td><%= post.created_at %></td>
  <td><%= link_to 'Show', post_comments_path(post) %></td>
</tr>

app/views/posts/index.html.erb
<h1> All posts </h1>

<table class="table">
  <tr>
    <th>Author</th>
    <th>Title</th>
    <th>Content</th>
    <th>Time</th>
    <th colspan="1">Watch comments</th>
  </tr>
  <%= render @posts %>
</table>

app/views/shared/_errors.html.erb
<% if resource.present? and resource.errors.present? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
    <h2> <%= pluralize(resource.errors.count, 'error') %> detected:</h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>